Register multiple font aliases
Apparently, there is recommended way to have OpenHTMl2PDF fall back to a
font in any case (whildcard), thus preventing errors like

```
ERROR 1 --- [html2pdf] [nio-8080-exec-6] c.h.m.services.html2pdf.MainController   : Error creating PDF
com.openhtmltopdf.pdfboxout.fontstore.FontNotFoundException: No font for the following specification has been found: Font specification: families: [Lato] size: 267.0 weight: normal style: normal variant: normal
       at com.openhtmltopdf.pdfboxout.PdfBoxFastOutputDevice.setFont(PdfBoxFastOutputDevice.java:388) ~[openhtmltopdf-pdfbox-1.1.31.jar!/:na]
       at com.openhtmltopdf.render.AbstractOutputDevice.drawText(AbstractOutputDevice.java:75) ~[openhtmltopdf-core-1.1.31.jar!/:na]
       at com.openhtmltopdf.render.InlineText.paint(InlineText.java:171) ~[openhtmltopdf-core-1.1.31.jar!/:na]
       at com.openhtmltopdf.render.InlineLayoutBox.paintInline(InlineLayoutBox.java:287) ~[openhtmltopdf-core-1.1.31.jar!/:na]
       at com.openhtmltopdf.render.displaylist.DisplayListPainter.paintInlineContent(DisplayListPainter.java:135) ~[openhtmltopdf-core-1.1.31.jar!/:na]
       at com.openhtmltopdf.render.displaylist.DisplayListPainter.paint(DisplayListPainter.java:262) ~[openhtmltopdf-core-1.1.31.jar!/:na]
       at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.paintPageFast(PdfBoxRenderer.java:883) ~[openhtmltopdf-pdfbox-1.1.31.jar!/:na]
       at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.writePDFFast(PdfBoxRenderer.java:596) ~[openhtmltopdf-pdfbox-1.1.31.jar!/:na]
       at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPdfFast(PdfBoxRenderer.java:496) ~[openhtmltopdf-pdfbox-1.1.31.jar!/:na]
       at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.createPDF(PdfBoxRenderer.java:427) ~[openhtmltopdf-pdfbox-1.1.31.jar!/:na]
       at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:44) ~[openhtmltopdf-pdfbox-1.1.31.jar!/:na]
       at com.hallowelt.mediawiki.services.html2pdf.MainController.renderPDF(MainController.java:106) ~[!/:1.0.6-SNAPSHOT]
       at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
```

ERM43194